use univers;

-- задание 1
SELECT
    at.AUDITORIUM_TYPENAME AS AUDITORIUM_TYPE_NAME, 
    MAX(a.AUDITORIUM_CAPACITY) AS MAX_CAPACITY,    
    MIN(a.AUDITORIUM_CAPACITY) AS MIN_CAPACITY,    
    AVG(a.AUDITORIUM_CAPACITY) AS AVG_CAPACITY,     
    SUM(a.AUDITORIUM_CAPACITY) AS TOTAL_CAPACITY,   
    COUNT(a.AUDITORIUM) AS AUDITORIUM_COUNT         
FROM AUDITORIUM a INNER JOIN AUDITORIUM_TYPE at
ON a.AUDITORIUM_TYPE = at.AUDITORIUM_TYPE
GROUP BY at.AUDITORIUM_TYPENAME;

-- задание 2
SELECT NOTE AS EXAM_NOTE, NOTE_COUNT                 
FROM (
    SELECT NOTE, COUNT(*) AS NOTE_COUNT     
    FROM PROGRESS
    WHERE NOTE BETWEEN 4 AND 10    
    GROUP BY NOTE                   
) AS NOTE_STATS
ORDER BY EXAM_NOTE DESC;              

-- задание 3
SELECT 
    F.FACULTY_NAME AS Faculty,
    G.PROFESSION AS Profession,
    YEAR(GETDATE()) - G.YEAR_FIRST + 1 AS Course,
    ROUND(AVG(CAST(P.NOTE AS FLOAT)), 2) AS AvgNote
FROM 
    PROGRESS P
    INNER JOIN STUDENT S ON P.IDSTUDENT = S.IDSTUDENT
    INNER JOIN GROUPS G ON S.IDGROUP = G.IDGROUP
    INNER JOIN FACULTY F ON G.FACULTY = F.FACULTY
GROUP BY 
    F.FACULTY_NAME, 
    G.PROFESSION, 
    YEAR(GETDATE()) - G.YEAR_FIRST
ORDER BY 
    AvgNote DESC;

-- задание 4
SELECT 
    F.FACULTY_NAME AS Faculty,
    G.PROFESSION AS Profession,
    YEAR(GETDATE()) - G.YEAR_FIRST + 1 AS Course,
    ROUND(AVG(CAST(P.NOTE AS FLOAT)), 2) AS AvgNote
FROM 
    PROGRESS P
    INNER JOIN STUDENT S ON P.IDSTUDENT = S.IDSTUDENT
    INNER JOIN GROUPS G ON S.IDGROUP = G.IDGROUP
    INNER JOIN FACULTY F ON G.FACULTY = F.FACULTY
WHERE 
    P.SUBJECT IN ('БД', 'ОАиП')
GROUP BY 
    F.FACULTY_NAME, 
    G.PROFESSION, 
    YEAR(GETDATE()) - G.YEAR_FIRST
ORDER BY 
    AvgNote DESC;

-- задание 5
SELECT 
    G.PROFESSION AS Profession,
    P.SUBJECT AS Subject,
    ROUND(AVG(CAST(P.NOTE AS FLOAT)), 2) AS AvgNote
FROM 
    PROGRESS P
    INNER JOIN STUDENT S ON P.IDSTUDENT = S.IDSTUDENT
    INNER JOIN GROUPS G ON S.IDGROUP = G.IDGROUP
    INNER JOIN FACULTY F ON G.FACULTY = F.FACULTY
WHERE 
    F.FACULTY = 'ИТ'
GROUP BY 
    G.PROFESSION, 
    P.SUBJECT
ORDER BY 
    G.PROFESSION, 
    AvgNote DESC;

-- задание 6
SELECT 
    SUBJECT AS Discipline,
    COUNT(IDSTUDENT) AS StudentsWith8or9
FROM 
    PROGRESS
WHERE 
    NOTE IN (8, 9)
GROUP BY 
    SUBJECT
HAVING 
    COUNT(IDSTUDENT) > 0
ORDER BY 
    StudentsWith8or9 DESC;

