USE univers;

-- 1
SELECT g.PROFESSION, p.SUBJECT,ROUND(AVG(CAST(p.NOTE AS FLOAT)), 2) AS AVG_GRADE
	FROM FACULTY f INNER JOIN GROUPS g 
	ON f.FACULTY = g.FACULTY INNER JOIN  STUDENT s 
	ON g.IDGROUP = s.IDGROUP INNER JOIN  PROGRESS p 
	ON s.IDSTUDENT = p.IDSTUDENT
	WHERE f.FACULTY = 'ศา' 
		GROUP BY ROLLUP(g.PROFESSION, p.SUBJECT) 
			ORDER BY  g.PROFESSION, p.SUBJECT;

-- 2
SELECT g.PROFESSION, p.SUBJECT,ROUND(AVG(CAST(p.NOTE AS FLOAT)), 2) AS AVG_GRADE
	FROM FACULTY f INNER JOIN GROUPS g 
	ON f.FACULTY = g.FACULTY INNER JOIN  STUDENT s	
	ON g.IDGROUP = s.IDGROUP INNER JOIN  PROGRESS p 
	ON s.IDSTUDENT = p.IDSTUDENT
	WHERE f.FACULTY = 'ศา' 
		GROUP BY CUBE(g.PROFESSION, p.SUBJECT) 
			ORDER BY  g.PROFESSION, p.SUBJECT;

-- 3
SELECT g.PROFESSION, p.SUBJECT,ROUND(AVG(CAST(p.NOTE AS FLOAT)), 2) AS AVG_GRADE
	FROM FACULTY f INNER JOIN GROUPS g 
	ON f.FACULTY = g.FACULTY INNER JOIN STUDENT s
	ON g.IDGROUP = s.IDGROUP INNER JOIN  PROGRESS p 
	ON s.IDSTUDENT = p.IDSTUDENT
	WHERE g.FACULTY = 'ศา' 
		GROUP BY g.PROFESSION, p.SUBJECT

	UNION

SELECT g.PROFESSION, p.SUBJECT,ROUND(AVG(CAST(p.NOTE AS FLOAT)), 2) AS AVG_GRADE
FROM FACULTY f INNER JOIN GROUPS g 
	ON f.FACULTY = g.FACULTY INNER JOIN STUDENT s
	ON g.IDGROUP = s.IDGROUP INNER JOIN  PROGRESS p 
	ON s.IDSTUDENT = p.IDSTUDENT
	WHERE g.FACULTY = 'ศา' 
		GROUP BY g.PROFESSION, p.SUBJECT
			ORDER BY g.PROFESSION, AVG_GRADE DESC;



SELECT g.PROFESSION, p.SUBJECT,ROUND(AVG(CAST(p.NOTE AS FLOAT)), 2) AS AVG_GRADE
	FROM FACULTY f INNER JOIN GROUPS g 
	ON f.FACULTY = g.FACULTY INNER JOIN STUDENT s
	ON g.IDGROUP = s.IDGROUP INNER JOIN  PROGRESS p 
	ON s.IDSTUDENT = p.IDSTUDENT
	WHERE g.FACULTY = 'ศา' 
		GROUP BY g.PROFESSION, p.SUBJECT

	UNION ALL

SELECT g.PROFESSION, p.SUBJECT,ROUND(AVG(CAST(p.NOTE AS FLOAT)), 2) AS AVG_GRADE
FROM FACULTY f INNER JOIN GROUPS g 
	ON f.FACULTY = g.FACULTY INNER JOIN STUDENT s
	ON g.IDGROUP = s.IDGROUP INNER JOIN  PROGRESS p 
	ON s.IDSTUDENT = p.IDSTUDENT
	WHERE g.FACULTY = 'ศา' 
		GROUP BY g.PROFESSION, p.SUBJECT
			ORDER BY g.PROFESSION, AVG_GRADE DESC;

-- 4
SELECT g.PROFESSION, p.SUBJECT,ROUND(AVG(CAST(p.NOTE AS FLOAT)), 2) AS AVG_GRADE
	FROM FACULTY f INNER JOIN GROUPS g 
	ON f.FACULTY = g.FACULTY INNER JOIN STUDENT s
	ON g.IDGROUP = s.IDGROUP INNER JOIN  PROGRESS p 
	ON s.IDSTUDENT = p.IDSTUDENT
	WHERE g.FACULTY = 'ศา' 
		GROUP BY g.PROFESSION, p.SUBJECT

	INTERSECT

SELECT g.PROFESSION, p.SUBJECT,ROUND(AVG(CAST(p.NOTE AS FLOAT)), 2) AS AVG_GRADE
FROM FACULTY f INNER JOIN GROUPS g 
	ON f.FACULTY = g.FACULTY INNER JOIN STUDENT s
	ON g.IDGROUP = s.IDGROUP INNER JOIN  PROGRESS p 
	ON s.IDSTUDENT = p.IDSTUDENT
	WHERE g.FACULTY = 'าฮย' 
		GROUP BY g.PROFESSION, p.SUBJECT
			ORDER BY g.PROFESSION, AVG_GRADE DESC;

-- 5
SELECT g.PROFESSION, p.SUBJECT,ROUND(AVG(CAST(p.NOTE AS FLOAT)), 2) AS AVG_GRADE
	FROM FACULTY f INNER JOIN GROUPS g 
	ON f.FACULTY = g.FACULTY INNER JOIN STUDENT s
	ON g.IDGROUP = s.IDGROUP INNER JOIN  PROGRESS p 
	ON s.IDSTUDENT = p.IDSTUDENT
	WHERE g.FACULTY = 'ศา' 
		GROUP BY g.PROFESSION, p.SUBJECT

	EXCEPT

SELECT g.PROFESSION, p.SUBJECT,ROUND(AVG(CAST(p.NOTE AS FLOAT)), 2) AS AVG_GRADE
FROM FACULTY f INNER JOIN GROUPS g 
	ON f.FACULTY = g.FACULTY INNER JOIN STUDENT s
	ON g.IDGROUP = s.IDGROUP INNER JOIN  PROGRESS p 
	ON s.IDSTUDENT = p.IDSTUDENT
	WHERE g.FACULTY = 'าฮย' 
		GROUP BY g.PROFESSION, p.SUBJECT
			ORDER BY g.PROFESSION, AVG_GRADE DESC;

GO

