use univers;
-- 1

DEALLOCATE PULPIT_CURSOR

DECLARE PULPIT_CURSOR CURSOR 
	FOR SELECT SUBJECT FROM SUBJECT
		WHERE PULPIT = '»Ò»“';

DECLARE @TMP CHAR(100), @T CHAR(100) = ' ';

OPEN PULPIT_CURSOR;
FETCH PULPIT_CURSOR INTO @TMP;
PRINT 'ƒ»—÷»œÀ»Õ€';
WHILE @@FETCH_STATUS = 0
	BEGIN
		SET @T = RTRIM(@TMP) + ', ' + @T;
		FETCH PULPIT_CURSOR INTO @TMP;
	END
PRINT @T
CLOSE PULPIT_CURSOR;

-- 2

DECLARE AUDITORIUMS CURSOR LOCAL                            
    FOR SELECT AUDITORIUM_TYPE, AUDITORIUM_CAPACITY FROM AUDITORIUM;

DECLARE @aud_type char(20), @aud_cap int;      
OPEN AUDITORIUMS;      

FETCH AUDITORIUMS INTO @aud_type, @aud_cap;   
PRINT '1. ' + @aud_type + CAST(@aud_cap AS varchar(6));   

FETCH AUDITORIUMS INTO @aud_type, @aud_cap;   
PRINT '2. ' + @aud_type + CAST(@aud_cap AS varchar(6));  

CLOSE AUDITORIUMS;  


DECLARE AUDITORIUMS CURSOR GLOBAL                            
    FOR SELECT AUDITORIUM_TYPE, AUDITORIUM_CAPACITY FROM AUDITORIUM;

DECLARE @aud_type_global char(20), @aud_cap_global int;      
OPEN AUDITORIUMS;      

FETCH AUDITORIUMS INTO @aud_type_global, @aud_cap_global;   
PRINT '1. ' + @aud_type_global + CAST(@aud_cap_global AS varchar(6));   

FETCH AUDITORIUMS INTO @aud_type_global, @aud_cap_global;   
PRINT '2. ' + @aud_type_global + CAST(@aud_cap_global AS varchar(6));  

CLOSE AUDITORIUMS;  
DEALLOCATE AUDITORIUMS;

-- 3

DECLARE @idstudent INT, @note INT;
DECLARE STATIC_CURSOR CURSOR STATIC
	FOR SELECT IDSTUDENT, NOTE 
		FROM PROGRESS
			WHERE SUBJECT = 'Í√';

SELECT IDSTUDENT, NOTE FROM PROGRESS WHERE SUBJECT = ' √';

OPEN STATIC_CURSOR;
FETCH STATIC_CURSOR INTO @idstudent, @note;

WHILE @@FETCH_STATUS = 0
BEGIN 
	UPDATE PROGRESS SET NOTE = 7 WHERE IDSTUDENT = @idstudent;
	FETCH NEXT FROM STATIC_CURSOR INTO @idstudent, @note;
END

SELECT IDSTUDENT, NOTE FROM PROGRESS WHERE SUBJECT = ' √';

CLOSE STATIC_CURSOR;
DEALLOCATE STATIC_CURSOR;


DECLARE @StudentID INT, @NoteStudent INT;
DECLARE DYNAMIC_CURSOR CURSOR DYNAMIC FOR
	SELECT IDSTUDENT, NOTE 
		FROM PROGRESS
			WHERE NOTE IS NOT NULL;

SELECT IDSTUDENT, NOTE 
		FROM PROGRESS
			WHERE NOTE IS NOT NULL;

OPEN DYNAMIC_CURSOR;
FETCH NEXT FROM DYNAMIC_CURSOR INTO @StudentID, @NoteStudent;

WHILE @@FETCH_STATUS = 0
BEGIN
    UPDATE PROGRESS SET NOTE = NOTE - 1 WHERE IDSTUDENT = @StudentID AND NOTE < 10;
    FETCH NEXT FROM dynamic_cursor INTO @StudentID, @NoteStudent;
END;

SELECT IDSTUDENT, NOTE 
		FROM PROGRESS
			WHERE NOTE IS NOT NULL;

CLOSE DYNAMIC_CURSOR;
DEALLOCATE DYNAMIC_CURSOR;

-- 4

SELECT PULPIT FROM PULPIT

DECLARE @CH CHAR(100)
DECLARE PULCUR CURSOR LOCAL SCROLL
	FOR SELECT PULPIT FROM PULPIT

OPEN PULCUR
FETCH FIRST FROM PULCUR INTO @CH
PRINT 'FIRST : ' + @CH
FETCH NEXT FROM PULCUR INTO @CH
PRINT 'NEXT : ' + @CH
FETCH PRIOR FROM PULCUR INTO @CH
PRINT 'PRIOR : ' + @CH
FETCH ABSOLUTE 3 FROM PULCUR INTO @CH
PRINT 'ABSOLUTE 3 : ' + @CH
FETCH ABSOLUTE -3 FROM PULCUR INTO @CH
PRINT 'ABSOLUTE -3 : ' + @CH
FETCH RELATIVE 5 FROM PULCUR INTO @CH
PRINT 'RELATIVE 5 : ' + @CH
FETCH RELATIVE -5 FROM PULCUR INTO @CH
PRINT 'RELATIVE -5 : ' + @CH

-- 5

SELECT * FROM PROGRESS;

DECLARE @ID INT, @NOOTE INT;
DECLARE DYNAMIC_CURSOR_FIVE CURSOR DYNAMIC
    FOR SELECT IDSTUDENT, NOTE 
        FROM PROGRESS FOR UPDATE;

OPEN DYNAMIC_CURSOR_FIVE;
FETCH DYNAMIC_CURSOR_FIVE INTO @ID, @NOOTE;

WHILE @@FETCH_STATUS = 0
BEGIN
    UPDATE PROGRESS SET NOTE = @NOOTE - 1 
    WHERE CURRENT OF DYNAMIC_CURSOR_FIVE;

    FETCH DYNAMIC_CURSOR_FIVE INTO @ID, @NOOTE;

END;

CLOSE DYNAMIC_CURSOR_FIVE;
DEALLOCATE DYNAMIC_CURSOR_FIVE;

SELECT * FROM PROGRESS;

-- 6
-- 6.1
DECLARE @MARK INT
DECLARE LOW4 CURSOR LOCAL DYNAMIC 
	FOR SELECT NOTE FROM PROGRESS LEFT OUTER JOIN STUDENT 
					ON PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT LEFT OUTER JOIN GROUPS
					ON STUDENT.IDGROUP = GROUPS.IDGROUP FOR UPDATE
OPEN LOW4
FETCH LOW4 INTO @MARK
WHILE @@FETCH_STATUS = 0
BEGIN
	PRINT @@FETCH_STATUS + ' ' + @MARK
	FETCH NEXT FROM LOW4 INTO @MARK
	IF @MARK <= 4
	BEGIN
		DELETE PROGRESS WHERE CURRENT OF LOW4
	END

END

-- 6.2
DECLARE @IDSTUD INT
DECLARE CORRECT CURSOR LOCAL DYNAMIC 
	FOR SELECT IDSTUDENT FROM PROGRESS FOR UPDATE
OPEN CORRECT
FETCH CORRECT INTO @IDSTUD
WHILE @@FETCH_STATUS = 0
BEGIN
	PRINT @@FETCH_STATUS + ' ' + @IDSTUD
	FETCH NEXT FROM CORRECT INTO @IDSTUD
	IF @IDSTUD = 1019
	BEGIN
		UPDATE PROGRESS SET NOTE += 1 WHERE CURRENT OF CORRECT
	END
END

