use univers;

/*1*/
CREATE VIEW опеондюбюрекэ 
AS SELECT TEACHER, TEACHER_NAME, GENDER, PULPIT
FROM TEACHER
SELECT * FROM опеондюбюрекэ

/*2*/
CREATE VIEW [йнкхвеярбн йютедп]
AS SELECT FACULTY.FACULTY_NAME, COUNT(PULPIT.PULPIT) AS йнкхвеярбн 
FROM FACULTY INNER JOIN PULPIT 
ON FACULTY.FACULTY = PULPIT.FACULTY 
GROUP BY FACULTY.FACULTY_NAME
SELECT * FROM [йнкхвеярбн йютедп]

/*3*/
CREATE VIEW юсдхрнпхх
AS SELECT AUDITORIUM, AUDITORIUM_TYPE FROM AUDITORIUM
WHERE AUDITORIUM_TYPE LIKE 'кй%'
SELECT * FROM юсдхрнпхх
INSERT юсдхрнпхх VALUES ('111-1', 'кй');
UPDATE юсдхрнпхх SET AUDITORIUM = '109-1' WHERE AUDITORIUM = '111-1';

/*4*/
CREATE VIEW [кейжхнммше юсдхрнпхх]
AS SELECT AUDITORIUM, AUDITORIUM_TYPE FROM AUDITORIUM
WHERE AUDITORIUM_TYPE LIKE 'кй%'
WITH CHECK OPTION;
INSERT [кейжхнммше юсдхрнпхх] VALUES ('123-4', '')
SELECT * FROM [кейжхнммше юсдхрнпхх]

/*5*/
CREATE VIEW дХЯЖХОКХМШ
AS SELECT TOP 10 SUBJECT, SUBJECT_NAME, PULPIT
FROM SUBJECT
ORDER BY SUBJECT_NAME;
SELECT * FROM дХЯЖХОКХМШ;

/*6*/
ALTER VIEW [йнкхвеярбн йютедп] WITH SCHEMABINDING
AS SELECT FACULTY.FACULTY_NAME, COUNT(PULPIT.PULPIT) AS йнкхвеярбн_йютедп
FROM dbo.FACULTY FACULTY INNER JOIN dbo.PULPIT PULPIT
ON FACULTY.FACULTY = PULPIT.FACULTY
GROUP BY FACULTY.FACULTY_NAME;
SELECT * FROM [йнкхвеярбн йютедп];